version: '3.1'

services:
    ekspor-php-apache:
        build:
            args:
                container_project_path: /var/www/html/
                uid: 1000
                user: $USER
            context: .
            dockerfile: ./Dockerfile
        image: bagisto-php-apache
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - ./workspace/:/var/www/html/

    ekspor-mysql:
        image: 'mariadb:10'
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        volumes:
            - ./.configs/mysql-data:/var/lib/mysql/

    ekspor-phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: ekspor-mysql
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - '${FORWARD_PHPMYADMIN_PORT:-8080}:80'
